server:
  port: 8090

spring:
  application:
    name: "loans"
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://loansdb:${LOANS_DB_PORT}/${LOANS_DB_NAME}
    username: ${LOANS_DB_USER}
    password: ${LOANS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"